server {
    listen 80;
    server_tokens off;

    # 1. Запросы к админке Django
    location /admin/ {
        proxy_set_header Host $http_host;
        proxy_pass http://foodgram-back:8888/admin/;
    }

    # 2. Запросы к API бэкенда
    location /api/ {
        proxy_set_header Host $http_host;
        proxy_pass http://foodgram-back:8888/api/;
    }

    # 3. Документация API
    location /api/docs/ {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    # 4. Раздача статики бэкенда и фронтенда
    location /static/ {
        root /var/html/;
        try_files $uri $uri/ /index.html;
    }

    # 5. Раздача медиа-файлов (картинки рецептов)
    location /media/ {
        root /var/html/;
    }

    # 6. Все остальные запросы отдаем фронтенду
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
