# Generated by Django 6.1.1 on 2026-10-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_ingredient_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_link',
            field=models.CharField(blank=True, editable=False, max_length=10, unique=True, verbose_name='short link'),
        ),
        migrations.DeleteModel(
            name='ShortLink',
        ),
    ]
