# Generated by Django 6.1.1 on 2026-09-30 08:36

import users.tools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=users.tools.normalize_avatar_path, verbose_name='avatar'),
        ),
    ]
